"""Fit the half-suit value model, then report how good it actually is.

Collects, from self-play, one feature vector per (decision, unresolved
half-suit) computed from the ACTING SEAT's posterior, labelled with how that
half-suit eventually resolved from that seat's team's point of view. Fits a
three-class logistic model and reports held-out log-loss, accuracy, calibration,
and - the number that decides whether the model is worth anything - the
correlation between the model's value and the realised outcome.

Baselines it must beat to be worth using:
  * the class prior (predict the marginal frequencies, ignore the features);
  * the single best feature (team share), fitted alone.

Usage:  py scripts4/fit_hsvalue.py [n_games] [n_jobs]
"""

from __future__ import annotations

import json
import random
import sys
import time
from multiprocessing import Pool
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from fish.beliefs import BeliefState
from fish.cards import NUM_PLAYERS, team_of
from fish.engine import GameState
from fish.observation import Observation
from fish.rules import RuleConfig
from fish4.askfeat import DecisionContext
from fish4.hsvalue import (HS_FEATURES, N_HS_FEATURES, OUTCOME_NULL,
                           OUTCOME_THEM, OUTCOME_US, HalfSuitValue,
                           fit_multinomial, half_suit_features, log_loss)
from fish4.posterior import Posterior
from fish4.registry4 import make_agent

# Fit on data generated by the CHAMPION, not by an earlier policy: the
# value of a half-suit is a property of the play that follows, so a model
# fitted under weaker play would be calibrated for the wrong continuation.
SPEC = ("fishbot4", {"opponent_gamma": 0.35})


def one_game(args):
    """Return (X, y, game_id) for one self-play game."""
    seed, agent_seed, stride = args
    rules = RuleConfig()
    agents = [make_agent(SPEC) for _ in range(NUM_PLAYERS)]
    st = GameState.deal(rules, seed=seed)
    ar = random.Random(agent_seed)
    for p, a in enumerate(agents):
        a.begin_game(p, rules, ar.getrandbits(64))
    rng = random.Random(agent_seed ^ 0x5DEECE66D)
    rows = []          # (features, seat, half_suit)
    step = 0
    while not st.is_terminal and step < 600:
        p = st.turn
        obs = Observation.from_state(st, p)
        if step % stride == 0:
            bel = agents[p].bel
            # the agent has not yet updated for this observation; do it here so
            # the features match exactly what the policy would have seen
            bel.update(obs)
            post = Posterior(bel, rng, n_draws=agents[p].n_draws,
                             n_worlds=agents[p].n_worlds, mode="auto")
            ctx = DecisionContext(obs, bel, post)
            for hs in range(ctx.n_hs):
                if obs.set_winner[hs] is None:
                    rows.append((half_suit_features(ctx, hs), p, hs))
        st.apply(p, agents[p].act(obs))
        step += 1
    if not rows:
        return np.zeros((0, N_HS_FEATURES)), np.zeros(0, dtype=np.int64), seed
    X = np.stack([r[0] for r in rows])
    y = np.empty(len(rows), dtype=np.int64)
    for i, (_, seat, hs) in enumerate(rows):
        w = st.set_winner[hs]
        if w is None or w == -1:
            y[i] = OUTCOME_NULL
        elif w == team_of(seat):
            y[i] = OUTCOME_US
        else:
            y[i] = OUTCOME_THEM
    return X, y, seed


def main(n_games: int = 150, n_jobs: int = 3, stride: int = 2):
    t0 = time.time()
    jobs = [(60_000 + i, 70_000 + i, stride) for i in range(n_games)]
    Xs, ys, gid = [], [], []
    if n_jobs > 1:
        with Pool(n_jobs) as pool:
            for i, (X, y, seed) in enumerate(
                    pool.imap_unordered(one_game, jobs, chunksize=1)):
                if len(y):
                    Xs.append(X)
                    ys.append(y)
                    gid.append(np.full(len(y), seed))
                if (i + 1) % 10 == 0:
                    print(f"  {i+1}/{n_games} games "
                          f"({time.time()-t0:.0f}s)", file=sys.stderr, flush=True)
    else:
        for j in jobs:
            X, y, seed = one_game(j)
            if len(y):
                Xs.append(X)
                ys.append(y)
                gid.append(np.full(len(y), seed))
    X = np.concatenate(Xs)
    y = np.concatenate(ys)
    g = np.concatenate(gid)
    print(f"\ncollected {len(y)} labels from {n_games} games "
          f"({time.time()-t0:.0f}s)")
    freq = np.bincount(y, minlength=3) / len(y)
    print(f"class frequencies: us {freq[0]:.3f} them {freq[1]:.3f} "
          f"null {freq[2]:.3f}")

    # Split BY GAME, not by row: rows from the same game share the same
    # eventual outcomes and are strongly correlated, so a row-wise split would
    # leak the label across the boundary and flatter the model.
    games = np.unique(g)
    rs = np.random.RandomState(0)
    rs.shuffle(games)
    cut = int(0.75 * len(games))
    train_games = set(games[:cut].tolist())
    tr = np.array([gi in train_games for gi in g])
    te = ~tr
    print(f"train {tr.sum()} rows / {cut} games, "
          f"test {te.sum()} rows / {len(games)-cut} games")

    results = {}

    # baseline 1: class prior
    prior = np.bincount(y[tr], minlength=3) / tr.sum()
    prior_ll = float(-np.mean(np.log(np.maximum(prior[y[te]], 1e-12))))
    results["prior"] = {"log_loss": prior_ll}

    # baseline 2: team share alone (plus bias)
    idx = [HS_FEATURES.index("team_share"), HS_FEATURES.index("bias")]
    Xs1 = np.zeros_like(X)
    Xs1[:, idx] = X[:, idx]
    m1 = fit_multinomial(Xs1[tr], y[tr], l2=1.0, iters=1200, lr=0.2)
    results["team_share_only"] = {"log_loss": log_loss(m1, Xs1[te], y[te])}

    # the model
    best, best_ll = None, float("inf")
    for l2 in (0.03, 0.1, 0.3, 1.0, 3.0):
        m = fit_multinomial(X[tr], y[tr], l2=l2, iters=2500, lr=0.1)
        ll = log_loss(m, X[te], y[te])
        if ll < best_ll:
            best, best_ll = m, ll
        print(f"  l2={l2:<5} held-out log-loss {ll:.4f}")
    results["model"] = {"log_loss": best_ll}

    P = best.probs(X[te])
    acc = float(np.mean(np.argmax(P, axis=1) == y[te]))
    V = best.value(X[te])
    realised = np.where(y[te] == OUTCOME_US, 1.0,
                        np.where(y[te] == OUTCOME_THEM, -1.0, 0.0))
    corr = float(np.corrcoef(V, realised)[0, 1])
    bias = float(np.mean(V - realised))
    results["model"].update({"accuracy": acc, "corr_with_outcome": corr,
                             "mean_bias": bias})

    # reliability of P(us) in deciles
    calib = []
    pu = P[:, OUTCOME_US]
    for b in range(10):
        m_ = (pu >= b / 10) & (pu < (b + 1) / 10 + (1e-9 if b == 9 else 0))
        if m_.sum() >= 20:
            calib.append({"bin": b, "mean_p": float(pu[m_].mean()),
                          "freq": float(np.mean(y[te][m_] == OUTCOME_US)),
                          "n": int(m_.sum())})
    results["calibration"] = calib

    print(f"\nheld-out log-loss:  prior {prior_ll:.4f} | "
          f"team-share-only {results['team_share_only']['log_loss']:.4f} | "
          f"model {best_ll:.4f}")
    print(f"accuracy {acc:.4f}   corr(value, realised outcome) {corr:.4f}   "
          f"mean bias {bias:+.4f}")
    print("\nreliability of P(our team scores this half-suit):")
    for c in calib:
        print(f"  p in [{c['bin']/10:.1f},{(c['bin']+1)/10:.1f})  "
              f"mean {c['mean_p']:.3f}  actual {c['freq']:.3f}  n={c['n']}")

    coefs = {f: [round(float(best.W[k, i]), 4) for k in range(3)]
             for i, f in enumerate(HS_FEATURES)}
    print("\ncoefficients (us / them / null):")
    for f, c in coefs.items():
        print(f"  {f:18s} {c[0]:+8.3f} {c[1]:+8.3f} {c[2]:+8.3f}")

    out = ROOT / "checkpoints" / "hsvalue_v1.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    best.save(out)
    (ROOT / "results" / "hsvalue_fit.json").write_text(json.dumps(
        {"n_games": n_games, "n_labels": int(len(y)),
         "class_freq": freq.tolist(), "results": results,
         "coefficients": coefs}, indent=2))
    print(f"\nSaved model to {out}")


if __name__ == "__main__":
    main(int(sys.argv[1]) if len(sys.argv) > 1 else 150,
         int(sys.argv[2]) if len(sys.argv) > 2 else 3)
