"""Draw public/share.png, the image a shared link previews with.

WHY A SCRIPT AND NOT A DRAWING. The card states the version, and a version
baked into a PNG is the one copy `tests4/test_brand.py` cannot read -- it scans
text. So the card is generated from `fish4.brand` and regenerated by running
this, which makes the version on it a derived value like every other one.

WHY MATPLOTLIB. It ships DejaVu Sans inside the wheel, so the card renders the
same on a machine with no system fonts installed. Pillow would pick up whatever
happens to be in /usr/share/fonts, which on a clean container is nothing.

    py scripts4/make_share_card.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import matplotlib                                            # noqa: E402
matplotlib.use("Agg")
import matplotlib.pyplot as plt                              # noqa: E402
from matplotlib.patches import FancyBboxPatch                 # noqa: E402
from matplotlib.transforms import Affine2D                    # noqa: E402

from fish4.brand import FULL_NAME                            # noqa: E402

OUT = ROOT / "public" / "share.png"

#: The site's felt, and its ink on felt. Kept as literals rather than imported
#: from style.css: two files that must agree is a worse problem than one number
#: written twice, and this card is not themed -- a preview has no dark mode.
FELT = "#1d5942"
INK = "#f2f7f4"
DIM = "#a8c9ba"
GOLD = "#e8c56a"

#: 1200x630, the size link previews are rendered at. DPI is high and the
#: figure correspondingly small, so every `fontsize` below is in POINTS at 200
#: dpi: a 30pt heading is 30/72*200 = 83 pixels tall on the finished card.
#: Reading them as if they were pixels is what produced a first draft with the
#: title running off the right edge.
W, H, DPI = 1200, 630, 200


def main() -> int:
    fig = plt.figure(figsize=(W / DPI, H / DPI), dpi=DPI)
    ax = fig.add_axes((0, 0, 1, 1))
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")
    fig.patch.set_facecolor(FELT)

    # Three card faces, fanned, on the right. A suggestion of the table rather
    # than a picture of one -- at preview size a real hand is mush.
    for i, (x, y, rot, pip, col) in enumerate((
            (0.745, 0.17, 14, "A\u2660", "#16181c"),
            (0.818, 0.21, 2, "K\u2665", "#c22b2b"),
            (0.891, 0.17, -10, "9\u2663", "#16181c"))):
        card = FancyBboxPatch(
            (x, y), 0.072, 0.26,
            boxstyle="round,pad=0.004,rounding_size=0.016",
            facecolor="#f7f4ec", edgecolor="#cdc6b8", linewidth=1.1,
            zorder=2 + i, mutation_aspect=H / W)
        card.set_transform(
            Affine2D().rotate_deg_around(x + 0.036, y + 0.13, rot)
            + ax.transAxes)
        ax.add_patch(card)
        t = ax.text(x + 0.036, y + 0.13, pip, color=col, fontsize=15,
                    ha="center", va="center", zorder=2 + i,
                    family="DejaVu Sans", transform=ax.transAxes)
        t.set_rotation(rot)

    ax.text(0.065, 0.815, "Fish", color=DIM, fontsize=10.5,
            va="center", family="DejaVu Sans")
    ax.text(0.065, 0.665, FULL_NAME, color=INK, fontsize=31, weight="bold",
            va="center", family="DejaVu Sans")
    ax.text(0.065, 0.475,
            "Six-player Literature, played by an engine\n"
            "that tracks the public record exactly.",
            color=INK, fontsize=11.5, va="center", linespacing=1.55,
            family="DejaVu Sans")
    ax.text(0.065, 0.265,
            "Play it  \u00b7  watch it fight another engine  \u00b7  "
            "read the paper",
            color=GOLD, fontsize=9.5, va="center", family="DejaVu Sans")
    ax.text(0.065, 0.165, "fish-engine.vercel.app", color=DIM, fontsize=8.5,
            va="center", family="DejaVu Sans")

    # A hairline in the brand gold, to give the card an edge at small sizes.
    ax.plot([0.0, 1.0], [0.988, 0.988], color=GOLD, lw=2.5,
            transform=ax.transAxes, clip_on=False)

    OUT.parent.mkdir(exist_ok=True)
    fig.savefig(OUT, facecolor=FELT)
    plt.close(fig)
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
